### ISSUE TITLE
使用或覆盖了已过时的 API

### ISSUE THREAD

**Issue by yfming93** [EchoPuda/location_service_check_nullsafety#2]
注: /Users/mingo/.pub-cache/git/location_service_check_nullsafety-76373cc8dee11d065270059989bbf157bd0ea505/android/src/main/java/com/jomin/location_service_check/LocationServiceCeckPlugin.java使用或覆盖了已过时的 API。

**Comment by yfming93** [comment]
能不能移除过时的api

**Comment by EchoPuda** [comment]
@yfming93 
![image](https://github.com/EchoPuda/location_service_check_nullsafety/assets/48596516/852638aa-4a32-4b25-920b-19ae2e9b6222)
已更新使用最新的API。

但minSdkVersion 16，所以需要考虑旧SDK的使用，就是说这提示是去不掉的。

对于使用没有影响，真介意的话可本地自行去掉过时的代码。
